### ISSUE TITLE
z

### ISSUE THREAD

**Issue by greatramu** [niallobrien/Vue-Vuex-Firebase#2]

**Comment by niallobrien** [comment]
@greatramu Seeing as you edited and removed your message, here's what you originally posted: 
![image](https://cloud.githubusercontent.com/assets/1525669/22197972/4d7bec02-e14c-11e6-8b1a-c17897fb3c54.png)
First of all, "Is this a joke?" Nope.
"What's the point of using vuex-fire?" Good question. I'm not using Vue-Fire or Vuex-Fire in this example, however they probably should be removed as dependencies. It would have been nice for you to submit a PR instead of opening an issue with a bitchy title/comment & then hiding it in a hit-and-run manner.
"You should be mutating the vuex store..." I am, see https://github.com/niallobrien/Vue-Vuex-Firebase/blob/master/src/vuex/modules/messages.js#L9 where I have a store mutation method to add a new message to the store.
"...and the Firebase part is handled automatically by vuex-fire." Again, I'm not using Vue-Fire or Vuex-Fire in this example.
Please take more care when wording new issues you open to any repo, not just this one.

**Comment by greatramu** [comment]
@niallobrien hii, I apologize for my stupid comment. I realized my stupidity as soon as I created this issue, but did not see an option to delete it. That is why emptied the message. If possible, please delete this issue.

**Comment by niallobrien** [comment]
Hi @greatramu Thank you, I really do appreciate it.
So to clarify this repo a bit, my main purpose was to show how you can get data from Firebase and populate a store when you add new messages etc. There are certainly improvements that could be made eg. instead of using the Firebase API within the components, handle the fetching of data with the Flux pattern and populate the store that way.

This is by no means a complete example, but simply a beginning example of how you can use Firebase with Vue and Vuex without feeling that you have to use & depend on VueFire or VuexFire to accomplish the same results.

Regardless, thank you for checking out the repo and I hope it's helped in some way. :+1:
